#!/usr/bin/env python3
"""
Document Analyzer Operator - Backend Environment Generator

This script automatically generates a complete .env file with secure random keys
and sensible defaults, eliminating manual configuration.

Features:
- Generate secure random SECRET_KEY (32 bytes)
- Generate secure ENCRYPTION_KEY (Fernet key)
- Set default DATABASE_URL (localhost PostgreSQL)
- Set default REDIS_URL (localhost Redis)
- Set sensible defaults for all settings
- Create .env file automatically
- Backup existing .env if present
- Interactive mode (optional prompts) and non-interactive mode

Usage:
    python generate_env.py              # Non-interactive mode
    python generate_env.py --interactive # Interactive mode
    python generate_env.py --help        # Show help
"""

import os
import sys
import argparse
import secrets
import shutil
from pathlib import Path
from datetime import datetime

try:
    from cryptography.fernet import Fernet
except ImportError:
    print("Installing cryptography package...")
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "cryptography", "-q"])
    from cryptography.fernet import Fernet


def generate_secret_key() -> str:
    """Generate a secure random secret key (32 bytes, URL-safe base64 encoded)."""
    return secrets.token_urlsafe(32)


def generate_encryption_key() -> str:
    """Generate a secure Fernet encryption key."""
    return Fernet.generate_key().decode()


def generate_jwt_secret() -> str:
    """Generate a secure random JWT secret key."""
    return secrets.token_urlsafe(32)


def check_postgresql() -> bool:
    """Check if PostgreSQL is accessible on localhost."""
    try:
        import socket
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(2)
        result = sock.connect_ex(('localhost', 5432))
        sock.close()
        return result == 0
    except Exception:
        return False


def check_redis() -> bool:
    """Check if Redis is accessible on localhost."""
    try:
        import socket
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(2)
        result = sock.connect_ex(('localhost', 6379))
        sock.close()
        return result == 0
    except Exception:
        return False


def backup_env_file(env_path: Path) -> None:
    """Backup existing .env file with timestamp."""
    if env_path.exists():
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_path = env_path.parent / f".env.backup.{timestamp}"
        shutil.copy(env_path, backup_path)
        print(f"✓ Backed up existing .env to {backup_path}")


def get_user_input(prompt: str, default: str = "") -> str:
    """Get user input with optional default value."""
    if default:
        user_input = input(f"{prompt} [{default}]: ").strip()
        return user_input if user_input else default
    else:
        return input(f"{prompt}: ").strip()


def generate_env_content(args) -> str:
    """Generate the complete .env file content."""
    secret_key = generate_secret_key()
    encryption_key = generate_encryption_key()
    jwt_secret = generate_jwt_secret()
    
    # Database URL - use asyncpg for async support
    database_url = f"postgresql+asyncpg://{args.db_user}:{args.db_password}@{args.db_host}:{args.db_port}/{args.db_name}"
    
    # Redis URL
    redis_url = f"redis://{args.redis_host}:{args.redis_port}/{args.redis_db}"
    
    env_content = f"""# =============================================================================
# Document Analyzer Operator - Environment Configuration
# Auto-generated by scripts/generate_env.py
# Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
# =============================================================================

# =============================================================================
# Application Settings
# =============================================================================
APP_NAME=Document Analyzer Operator
APP_VERSION=0.1.0
APP_DEBUG={str(args.debug).lower()}
APP_ENVIRONMENT={args.env}
APP_API_PREFIX=/api/v1

# =============================================================================
# Server Settings
# =============================================================================
APP_HOST={args.host}
APP_PORT={args.port}
APP_WORKERS={args.workers}
APP_RELOAD={str(args.reload).lower()}

# =============================================================================
# Database Settings (PostgreSQL)
# =============================================================================
POSTGRES_USER={args.db_user}
POSTGRES_PASSWORD={args.db_password}
POSTGRES_HOST={args.db_host}
POSTGRES_PORT={args.db_port}
POSTGRES_DB={args.db_name}
DATABASE_URL={database_url}
DB_ECHO=false
DB_POOL_SIZE=10
DB_MAX_OVERFLOW=20
DB_POOL_TIMEOUT=30
DB_POOL_RECYCLE=1800

# =============================================================================
# Redis Settings
# =============================================================================
REDIS_HOST={args.redis_host}
REDIS_PORT={args.redis_port}
REDIS_DB={args.redis_db}
REDIS_PASSWORD=
REDIS_URL={redis_url}
REDIS_TTL=3600

# =============================================================================
# JWT Authentication
# =============================================================================
SECRET_KEY={secret_key}
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30
REFRESH_TOKEN_EXPIRE_DAYS=7
TOKEN_BLACKLIST_ENABLED=true

# =============================================================================
# CORS Settings
# =============================================================================
CORS_ORIGINS=http://localhost:3000,http://localhost:8000,http://localhost:8080
CORS_ALLOW_CREDENTIALS=true
CORS_ALLOW_METHODS=*
CORS_ALLOW_HEADERS=*

# =============================================================================
# Security Settings
# =============================================================================
BCRYPT_ROUNDS=12
RATE_LIMIT_REQUESTS=100
RATE_LIMIT_WINDOW=60

# =============================================================================
# API Key Encryption
# =============================================================================
ENCRYPTION_KEY={encryption_key}

# =============================================================================
# Default LLM Provider Settings
# =============================================================================
DEFAULT_LLM_PROVIDER=local

# =============================================================================
# OpenAI Settings
# Get your API key from: https://platform.openai.com/api-keys
# =============================================================================
OPENAI_API_KEY=
OPENAI_BASE_URL=https://api.openai.com/v1
OPENAI_MODEL=gpt-4

# =============================================================================
# Anthropic Settings
# Get your API key from: https://console.anthropic.com/settings/keys
# =============================================================================
ANTHROPIC_API_KEY=
ANTHROPIC_BASE_URL=https://api.anthropic.com/v1
ANTHROPIC_MODEL=claude-3-sonnet-20240229

# =============================================================================
# Groq Settings
# Get your API key from: https://console.groq.com/keys
# =============================================================================
GROQ_API_KEY=
GROQ_BASE_URL=https://api.groq.com/openai/v1
GROQ_MODEL=llama3-70b-8192

# =============================================================================
# Together AI Settings
# Get your API key from: https://api.together.ai/settings/api-keys
# =============================================================================
TOGETHER_API_KEY=
TOGETHER_BASE_URL=https://api.together.xyz/v1
TOGETHER_MODEL=meta-llama/Llama-3-70b-chat-hf

# =============================================================================
# Anyscale Settings
# Get your API key from: https://app.endpoints.anyscale.com/credentials
# =============================================================================
ANYSCALE_API_KEY=
ANYSCALE_BASE_URL=https://api.endpoints.anyscale.com/v1
ANYSCALE_MODEL=meta-llama/Llama-3-70b-chat-hf

# =============================================================================
# Ollama Settings (Local LLM)
# =============================================================================
OLLAMA_BASE_URL=http://localhost:11434
OLLAMA_MODEL=llama3

# =============================================================================
# LM Studio Settings (Local LLM)
# =============================================================================
LM_STUDIO_BASE_URL=http://localhost:1234/v1
LM_STUDIO_MODEL=local-model

# =============================================================================
# vLLM Settings (Local LLM)
# =============================================================================
VLLM_BASE_URL=http://localhost:8000/v1
VLLM_MODEL=facebook/opt-125m

# =============================================================================
# Custom Provider Settings
# =============================================================================
CUSTOM_BASE_URL=
CUSTOM_API_KEY=
CUSTOM_MODEL=

# =============================================================================
# File Storage Settings
# =============================================================================
STORAGE_PROVIDER=local
STORAGE_ROOT=./storage
STORAGE_TYPE=local
STORAGE_PATH=./storage

# For MinIO/S3 (uncomment and configure if needed):
# STORAGE_PROVIDER=minio
# STORAGE_ENDPOINT=localhost:9000
# STORAGE_ACCESS_KEY=minioadmin
# STORAGE_SECRET_KEY=minioadmin
# STORAGE_BUCKET=documents
# STORAGE_USE_SSL=false
# STORAGE_REGION=us-east-1

# =============================================================================
# Vector Database Settings (Qdrant)
# =============================================================================
QDRANT_URL=http://localhost:6333
QDRANT_API_KEY=

# =============================================================================
# Graph Database Settings (Neo4j)
# =============================================================================
NEO4J_URI=bolt://localhost:7687
NEO4J_USER=neo4j
NEO4J_PASSWORD=change_this_secure_password

# =============================================================================
# Workflow Engine Settings (Temporal)
# =============================================================================
TEMPORAL_HOST=localhost
TEMPORAL_PORT=7233
TEMPORAL_NAMESPACE=default

# =============================================================================
# Logging Settings
# =============================================================================
LOG_LEVEL={args.log_level}
LOG_FORMAT=%(asctime)s - %(name)s - %(levelname)s - %(message)s
LOG_FILE=logs/app.log

# =============================================================================
# Application Settings
# =============================================================================
UVICORN_WORKERS={args.workers}
MAX_UPLOAD_SIZE_MB=10

# =============================================================================
# Feature Flags
# =============================================================================
ENABLE_WEBSOCKET=true
ENABLE_ANALYTICS=true

# =============================================================================
# NATIVE SETUP INSTRUCTIONS
# =============================================================================
#
# For Docker deployment (default):
#   - Use docker-compose up to start all services
#   - PostgreSQL, Redis, etc. will run in containers
#   - Database URLs use container hostnames (e.g., postgres, redis)
#
# For Native deployment (no Docker):
#   - This .env is already configured for localhost
#   - Install PostgreSQL, Redis locally
#   - Run: ./setup_native.sh or setup_native.bat
#   - Start with: ./run_native.sh or run_native.bat
#
# =============================================================================
"""
    return env_content


def generate_env_file(args) -> bool:
    """Generate the .env file."""
    env_path = Path(__file__).parent.parent / ".env"
    
    # Check if .env exists and backup if needed
    if env_path.exists() and not args.force:
        if args.interactive:
            response = input(f"⚠ {env_path} already exists. Overwrite? (y/N): ").strip().lower()
            if response != 'y':
                print("✓ Keeping existing .env file")
                return False
        else:
            print(f"⚠ {env_path} already exists. Use --force to overwrite or --interactive for prompts")
            return False
    
    # Backup existing file
    if env_path.exists():
        backup_env_file(env_path)
    
    # Generate content
    env_content = generate_env_content(args)
    
    # Write to file
    env_path.write_text(env_content)
    
    print(f"✓ Generated .env file at {env_path}")
    print(f"✓ SECRET_KEY generated securely (32 bytes)")
    print(f"✓ ENCRYPTION_KEY generated securely (Fernet)")
    print(f"✓ JWT_SECRET_KEY generated securely")
    print(f"✓ DATABASE_URL configured for PostgreSQL at localhost:5432")
    print(f"✓ REDIS_URL configured for Redis at localhost:6379")
    
    # Service status
    print("\n📊 Service Detection:")
    if check_postgresql():
        print("  ✓ PostgreSQL detected on localhost:5432")
    else:
        print("  ⚠ PostgreSQL not detected on localhost:5432")
        print("    Install: https://www.postgresql.org/download/")
    
    if check_redis():
        print("  ✓ Redis detected on localhost:6379")
    else:
        print("  ⚠ Redis not detected on localhost:6379")
        print("    Install: https://redis.io/download/")
    
    print("\n⚠ Review and configure LLM API keys as needed:")
    print("  - OPENAI_API_KEY (https://platform.openai.com/api-keys)")
    print("  - ANTHROPIC_API_KEY (https://console.anthropic.com/settings/keys)")
    print("  - GROQ_API_KEY (https://console.groq.com/keys)")
    print("  - TOGETHER_API_KEY (https://api.together.ai/settings/api-keys)")
    print("  - ANYSCALE_API_KEY (https://app.endpoints.anyscale.com/credentials)")
    
    print("\n✓ Environment file generation complete!")
    return True


def interactive_setup() -> argparse.Namespace:
    """Run interactive setup to collect user preferences."""
    print("\n" + "="*60)
    print("Document Analyzer Operator - Interactive Environment Setup")
    print("="*60 + "\n")
    
    print("This wizard will help you configure your environment.")
    print("Press Enter to accept default values shown in [brackets].\n")
    
    # Application settings
    print("--- Application Settings ---")
    env = get_user_input("Environment (development/production)", "development")
    debug = get_user_input("Enable debug mode? (true/false)", "true").lower() == 'true'
    host = get_user_input("Host", "0.0.0.0")
    port = get_user_input("Port", "8000")
    workers = get_user_input("Number of workers", "4")
    reload = get_user_input("Enable auto-reload? (true/false)", "true").lower() == 'true'
    log_level = get_user_input("Log level (DEBUG/INFO/WARNING/ERROR)", "INFO")
    
    # Database settings
    print("\n--- Database Settings ---")
    db_host = get_user_input("Database host", "localhost")
    db_port = get_user_input("Database port", "5432")
    db_name = get_user_input("Database name", "document_analyzer")
    db_user = get_user_input("Database user", "document_user")
    db_password = get_user_input("Database password", "document_pass")
    
    # Redis settings
    print("\n--- Redis Settings ---")
    redis_host = get_user_input("Redis host", "localhost")
    redis_port = get_user_input("Redis port", "6379")
    redis_db = get_user_input("Redis database", "0")
    
    # Create args namespace
    args = argparse.Namespace(
        env=env,
        debug=debug,
        host=host,
        port=int(port),
        workers=int(workers),
        reload=reload,
        log_level=log_level.upper(),
        db_host=db_host,
        db_port=int(db_port),
        db_name=db_name,
        db_user=db_user,
        db_password=db_password,
        redis_host=redis_host,
        redis_port=int(redis_port),
        redis_db=redis_db,
        force=False,
        interactive=True
    )
    
    return args


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Generate .env file for Document Analyzer Operator backend",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python generate_env.py              # Non-interactive with defaults
  python generate_env.py --interactive # Interactive wizard
  python generate_env.py --force       # Overwrite existing .env
  python generate_env.py --env production  # Set environment
        """
    )
    
    parser.add_argument(
        "--interactive", "-i",
        action="store_true",
        help="Run interactive setup wizard"
    )
    
    parser.add_argument(
        "--force", "-f",
        action="store_true",
        help="Overwrite existing .env file without prompting"
    )
    
    parser.add_argument(
        "--env",
        choices=["development", "production", "staging"],
        default="development",
        help="Application environment (default: development)"
    )
    
    parser.add_argument(
        "--debug",
        action="store_true",
        default=True,
        help="Enable debug mode (default: true)"
    )
    
    parser.add_argument(
        "--host",
        default="0.0.0.0",
        help="Server host (default: 0.0.0.0)"
    )
    
    parser.add_argument(
        "--port",
        type=int,
        default=8000,
        help="Server port (default: 8000)"
    )
    
    parser.add_argument(
        "--workers",
        type=int,
        default=4,
        help="Number of workers (default: 4)"
    )

    parser.add_argument(
        "--reload",
        action="store_true",
        default=False,
        help="Enable auto-reload (default: false)"
    )

    parser.add_argument(
        "--log-level",
        choices=["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
        default="INFO",
        help="Logging level (default: INFO)"
    )
    
    parser.add_argument(
        "--db-host",
        default="localhost",
        help="Database host (default: localhost)"
    )
    
    parser.add_argument(
        "--db-port",
        type=int,
        default=5432,
        help="Database port (default: 5432)"
    )
    
    parser.add_argument(
        "--db-name",
        default="document_analyzer",
        help="Database name (default: document_analyzer)"
    )
    
    parser.add_argument(
        "--db-user",
        default="document_user",
        help="Database user (default: document_user)"
    )
    
    parser.add_argument(
        "--db-password",
        default="document_pass",
        help="Database password (default: document_pass)"
    )
    
    parser.add_argument(
        "--redis-host",
        default="localhost",
        help="Redis host (default: localhost)"
    )
    
    parser.add_argument(
        "--redis-port",
        type=int,
        default=6379,
        help="Redis port (default: 6379)"
    )
    
    parser.add_argument(
        "--redis-db",
        default="0",
        help="Redis database (default: 0)"
    )
    
    args = parser.parse_args()
    
    # Run interactive setup if requested
    if args.interactive:
        args = interactive_setup()
    
    # Generate the .env file
    success = generate_env_file(args)
    
    # Exit with appropriate code
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
