#!/usr/bin/env node
/**
 * Document Analyzer Operator - Frontend Environment Generator
 * 
 * This script automatically generates a complete .env.local file
 * with sensible defaults for the frontend application.
 * 
 * Features:
 * - Set NEXT_PUBLIC_API_URL for backend connection
 * - Set NEXT_PUBLIC_WS_URL for WebSocket connection
 * - Set NEXT_PUBLIC_ENABLE_WEBSOCKET
 * - Create .env.local automatically
 * - Backup existing .env.local
 * - Interactive mode (optional prompts) and non-interactive mode
 * 
 * Usage:
 *   node generate_env.js              # Non-interactive mode
 *   node generate_env.js --interactive # Interactive mode
 *   node generate_env.js --help        # Show help
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

/**
 * Get the directory containing this script
 */
const scriptDir = __dirname;
const rootDir = path.join(scriptDir, '..');
const envLocalPath = path.join(rootDir, '.env.local');

/**
 * Check if a port is in use
 */
function checkPort(port) {
    return new Promise((resolve) => {
        const net = require('net');
        const server = net.createServer();
        
        server.once('error', () => {
            resolve(false);
        });
        
        server.once('listening', () => {
            server.close();
            resolve(true);
        });
        
        server.listen(port);
    });
}

/**
 * Backup existing .env.local file with timestamp
 */
function backupEnvFile() {
    if (fs.existsSync(envLocalPath)) {
        const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
        const backupPath = path.join(rootDir, `.env.local.backup.${timestamp}`);
        fs.copyFileSync(envLocalPath, backupPath);
        console.log(`✓ Backed up existing .env.local to ${backupPath}`);
        return true;
    }
    return false;
}

/**
 * Generate .env.local content
 */
function generateEnvContent(config) {
    const timestamp = new Date().toLocaleString();
    
    return `# =============================================================================
# Document Analyzer Operator - Frontend Environment Configuration
# Auto-generated by scripts/generate_env.js
# Generated: ${timestamp}
# =============================================================================

# =============================================================================
# API Configuration
# For native setup, ensure backend is running on the specified URL
# =============================================================================
NEXT_PUBLIC_API_URL=${config.apiUrl}
NEXT_PUBLIC_WS_URL=${config.wsUrl}

# =============================================================================
# Application
# =============================================================================
NEXT_PUBLIC_APP_NAME=Document Analyzer Operator
NEXT_PUBLIC_APP_VERSION=1.0.0

# =============================================================================
# Auth
# =============================================================================
NEXT_PUBLIC_TOKEN_REFRESH_INTERVAL=1800000

# =============================================================================
# Features
# =============================================================================
NEXT_PUBLIC_ENABLE_WEBSOCKET=${config.enableWebSocket}
NEXT_PUBLIC_ENABLE_REALTIME_UPDATES=${config.enableRealtimeUpdates}

# =============================================================================
# Feature Flags
# =============================================================================
NEXT_PUBLIC_ENABLE_ANALYTICS=${config.enableAnalytics}
NEXT_PUBLIC_ENABLE_ERROR_BOUNDARY=true

# =============================================================================
# Development Settings
# =============================================================================
NEXT_PUBLIC_DEV_MODE=${config.devMode}
NEXT_PUBLIC_DEBUG=${config.debug}

# =============================================================================
# NATIVE SETUP NOTES
# =============================================================================
#
# For Docker deployment:
#   - API URL should point to the backend container
#   - Example: NEXT_PUBLIC_API_URL=http://localhost:8000
#
# For Native deployment:
#   - Same configuration works for native setup
#   - Ensure backend is running on localhost:8000
#   - Start backend with: cd ../backend && ./run_native.sh
#
# Production deployment:
#   - Update URLs to your production endpoints
#   - Example: NEXT_PUBLIC_API_URL=https://api.yourdomain.com
#
# =============================================================================
`;
}

/**
 * Generate the .env.local file
 */
async function generateEnvFile(config, force = false) {
    // Check if .env.local exists
    if (fs.existsSync(envLocalPath) && !force) {
        if (config.interactive) {
            const answer = await prompt(`⚠ .env.local already exists. Overwrite? (y/N): `);
            if (answer.toLowerCase() !== 'y') {
                console.log('✓ Keeping existing .env.local file');
                return false;
            }
        } else {
            console.log('⚠ .env.local already exists. Use --force to overwrite or --interactive for prompts');
            return false;
        }
    }
    
    // Backup existing file
    if (fs.existsSync(envLocalPath)) {
        backupEnvFile();
    }
    
    // Generate content
    const envContent = generateEnvContent(config);
    
    // Write to file
    fs.writeFileSync(envLocalPath, envContent);
    
    console.log(`✓ Generated .env.local file at ${envLocalPath}`);
    console.log(`✓ NEXT_PUBLIC_API_URL set to ${config.apiUrl}`);
    console.log(`✓ NEXT_PUBLIC_WS_URL set to ${config.wsUrl}`);
    console.log(`✓ WebSocket enabled: ${config.enableWebSocket}`);
    
    // Service detection
    console.log('\n📊 Service Detection:');
    
    const apiPort = parseInt(config.apiUrl.split(':').pop());
    const wsPort = parseInt(config.wsUrl.split(':').pop());
    
    const apiAvailable = await checkPort(apiPort);
    const wsAvailable = await checkPort(wsPort);
    
    if (!apiAvailable) {
        console.log(`  ✓ Port ${apiPort} is available (backend can bind)`);
    } else {
        console.log(`  ⚠ Port ${apiPort} appears to be in use`);
    }
    
    console.log('\n✓ Environment file generation complete!');
    return true;
}

/**
 * Prompt user for input
 */
function prompt(question) {
    const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
    });
    
    return new Promise((resolve) => {
        rl.question(question, (answer) => {
            rl.close();
            resolve(answer);
        });
    });
}

/**
 * Run interactive setup wizard
 */
async function interactiveSetup() {
    console.log('\n' + '='.repeat(60));
    console.log('Document Analyzer Operator - Interactive Frontend Setup');
    console.log('='.repeat(60) + '\n');
    
    console.log('This wizard will help you configure your frontend environment.');
    console.log('Press Enter to accept default values shown in [brackets].\n');
    
    // API settings
    console.log('--- API Configuration ---');
    const apiUrl = await prompt(`Backend API URL [http://localhost:8000]: `) || 'http://localhost:8000';
    const wsUrl = await prompt(`WebSocket URL [ws://localhost:8000]: `) || 'ws://localhost:8000';
    
    // Feature flags
    console.log('\n--- Feature Flags ---');
    const enableWebSocket = (await prompt(`Enable WebSocket? (true/false) [true]: `) || 'true').toLowerCase() === 'true';
    const enableRealtimeUpdates = (await prompt(`Enable real-time updates? (true/false) [true]: `) || 'true').toLowerCase() === 'true';
    const enableAnalytics = (await prompt(`Enable analytics? (true/false) [false]: `) || 'false').toLowerCase() === 'true';
    
    // Development settings
    console.log('\n--- Development Settings ---');
    const devMode = (await prompt(`Enable dev mode? (true/false) [true]: `) || 'true').toLowerCase() === 'true';
    const debug = (await prompt(`Enable debug? (true/false) [true]: `) || 'true').toLowerCase() === 'true';
    
    return {
        apiUrl,
        wsUrl,
        enableWebSocket,
        enableRealtimeUpdates,
        enableAnalytics,
        devMode,
        debug,
        interactive: true
    };
}

/**
 * Parse command line arguments
 */
function parseArgs() {
    const args = {
        interactive: false,
        force: false,
        apiUrl: 'http://localhost:8000',
        wsUrl: 'ws://localhost:8000',
        enableWebSocket: 'true',
        enableRealtimeUpdates: 'true',
        enableAnalytics: 'false',
        devMode: 'true',
        debug: 'true'
    };
    
    const argList = process.argv.slice(2);
    
    for (let i = 0; i < argList.length; i++) {
        const arg = argList[i];
        
        if (arg === '--interactive' || arg === '-i') {
            args.interactive = true;
        } else if (arg === '--force' || arg === '-f') {
            args.force = true;
        } else if (arg === '--api-url' && argList[i + 1]) {
            args.apiUrl = argList[++i];
        } else if (arg === '--ws-url' && argList[i + 1]) {
            args.wsUrl = argList[++i];
        } else if (arg === '--help' || arg === '-h') {
            console.log(`
Frontend Environment Generator

Usage:
  node generate_env.js              # Non-interactive with defaults
  node generate_env.js --interactive # Interactive wizard
  node generate_env.js --force       # Overwrite existing .env.local
  node generate_env.js --api-url <url>  # Set custom API URL

Options:
  -i, --interactive     Run interactive setup wizard
  -f, --force           Overwrite existing .env.local without prompting
  --api-url <url>       Set backend API URL (default: http://localhost:8000)
  --ws-url <url>        Set WebSocket URL (default: ws://localhost:8000)
  -h, --help            Show this help message
`);
            process.exit(0);
        }
    }
    
    return args;
}

/**
 * Main entry point
 */
async function main() {
    const args = parseArgs();
    
    // Run interactive setup if requested
    let config;
    if (args.interactive) {
        config = await interactiveSetup();
    } else {
        config = {
            apiUrl: args.apiUrl,
            wsUrl: args.wsUrl,
            enableWebSocket: args.enableWebSocket,
            enableRealtimeUpdates: args.enableRealtimeUpdates,
            enableAnalytics: args.enableAnalytics,
            devMode: args.devMode,
            debug: args.debug,
            interactive: false
        };
    }
    
    // Generate the .env.local file
    const success = await generateEnvFile(config, args.force);
    
    // Exit with appropriate code
    process.exit(success ? 0 : 1);
}

// Run main function
main().catch((error) => {
    console.error('❌ Error:', error.message);
    process.exit(1);
});
